# Site settings
title: Becoming [ICBacon](github.com/icbacon)
email: ibacon@continuum.io
description: > # this means to ignore newlines until "baseurl:"
  A story about my internship in reproducible science at [Continuum Analytics](http://continuum.io/)
  using [Anaconda](https://anaconda.org/).
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://icbacon.github.io # the base hostname & protocol for your site

## Social media accounts

disqus_username: icbacon

twitter_username: IanCBacon
github:
  username: icbacon
  repository: icbacon.github.io

# Build settings
markdown: kramdown
