# Site settings
title: Intern at Continuum
email: ibacon@continuum.io
description: > # this means to ignore newlines until "baseurl:"
  Interning at Continuum under the direction of Tony Fast 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://icbacon.github.io # the base hostname & protocol for your site

## Social media accounts

disqus_username: icbacon

twitter_username: IanCBacon
github:
  username: icbacon
  repository: icbacon.github.io

# Build settings
markdown: kramdown
